version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gosec:
      excludes:
        - G115
        - G204
        - G304
        - G703
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
